site_name: Complib Help
nav:
  - Introduction: index.md
  - Core concepts: concepts.md
  - 'Methods': 
    - Method pages: methods/overview.md
    - Customising blue lines: methods/blueline_options.md
    - Understanding method properties: methods/method_properties.md
    - Place notation: methods/place_notation.md
    - Adding methods: methods/adding_methods.md
  - 'Compositions':
    - Composition pages: compositions/overview.md
  - 'Collections':
    - Overview: collections/overview.md
  - 'Searching Complib':
    - Search by title or filter: search/basic.md
    - Extended search: search/extended.md
  - 'Advanced Topics':
    - Row parity: advanced/row_parity.md
    - Leadhead codes: advanced/leadhead_codes.md
    - Extensions: advanced/extensions.md
    - False coursehead (FCH) groups: advanced/fch_groups.md
  - 'Additional Info':
    - About: about.md
theme: readthedocs
markdown_extensions: 
  - admonition
  - def_list
  - attr_list
